
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    sellerId: 'u2',
    name: 'Premium Cotton Hoodie (Navy)',
    description: 'High-quality cotton blend hoodie. Perfect for cold weather and casual outings.',
    price: 12000,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=1',
    rating: 4.8,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '2',
    sellerId: 'u2',
    name: 'Atomic Habits by James Clear',
    description: 'The #1 New York Times bestseller. An easy and proven way to build good habits.',
    price: 4500,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.9,
    inStock: true,
    estimatedDelivery: 'Same day',
  },
  {
    id: '3',
    sellerId: 'u2',
    name: 'Performance Sports Jersey',
    description: 'Breathable, moisture-wicking fabric suitable for football and gym activities.',
    price: 6000,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.7,
    inStock: true,
    estimatedDelivery: '2 days',
  },
  {
    id: '4',
    sellerId: 'u2',
    name: 'Tech Weekly Magazine',
    description: 'Stay updated with the latest trends in technology and startups.',
    price: 500,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.2,
    inStock: true,
    estimatedDelivery: 'Instant',
  },
  {
    id: '5',
    sellerId: 'u2',
    name: 'Grill Special Platter',
    description: 'Spicy grilled meat with sides of onions and peppers. Freshly prepared.',
    price: 3500,
    category: 'Food',
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.7,
    inStock: true,
    estimatedDelivery: '45 mins',
  },
  {
    id: '6',
    sellerId: 'u2',
    name: 'Portable Rechargeable Fan',
    description: 'Keep cool anywhere. Long-lasting battery life with 3 speed settings.',
    price: 8500,
    category: 'Home',
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.6,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '7',
    sellerId: 'u2',
    name: 'Scientific Calculator fx-991EX',
    description: 'Advanced calculator for engineering and science professionals.',
    price: 15000,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=7',
    rating: 5.0,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '8',
    sellerId: 'u2',
    name: 'Noodle Combo Pack',
    description: 'Quick and delicious meal pack. Includes spices and vegetables.',
    price: 1800,
    category: 'Food',
    image: 'https://picsum.photos/400/400?random=8',
    rating: 4.4,
    inStock: true,
    estimatedDelivery: '30 mins',
  },
  {
    id: '9',
    sellerId: 'u2',
    name: 'Household Bucket Set',
    description: 'Durable plastic bucket and bowl set for everyday home use.',
    price: 3000,
    category: 'Home',
    image: 'https://picsum.photos/400/400?random=9',
    rating: 4.1,
    inStock: true,
    estimatedDelivery: 'Same day',
  },
  {
    id: '10',
    sellerId: 'u2',
    name: 'Luxury Varsity Jacket',
    description: 'Limited edition gold and white varsity jacket. Premium stitching.',
    price: 18000,
    category: 'Fashion',
    image: 'https://picsum.photos/400/400?random=10',
    rating: 4.9,
    inStock: false,
    estimatedDelivery: '3-5 days',
  },
  {
    id: '11',
    sellerId: 'u2',
    name: 'Power Bank 20000mAh',
    description: 'Fast charging power bank compatible with all smartphones.',
    price: 12000,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=11',
    rating: 4.7,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '12',
    sellerId: 'u2',
    name: 'Professional Resume Template',
    description: 'Editable word document template to land your dream job.',
    price: 1500,
    category: 'Services',
    image: 'https://picsum.photos/400/400?random=12',
    rating: 4.8,
    inStock: true,
    estimatedDelivery: 'Instant PDF',
  }
];
