
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    sellerId: 'u2',
    name: 'UI Official Hoodie (Blue)',
    description: 'Premium cotton blend hoodie with the embroidered University of Ibadan crest. Perfect for chilly lectures.',
    price: 12000,
    category: 'Merch',
    image: 'https://picsum.photos/400/400?random=1',
    rating: 4.8,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '2',
    sellerId: 'u2',
    name: 'Intro to Philosophy - 100L',
    description: 'Essential textbook for all freshers taking GES courses. Latest edition.',
    price: 2500,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=2',
    rating: 4.5,
    inStock: true,
    estimatedDelivery: 'Same day',
  },
  {
    id: '3',
    sellerId: 'u2',
    name: 'Zik Hall Jersey',
    description: 'Show your hall pride with this authentic Nnamdi Azikiwe Hall sports jersey.',
    price: 6000,
    category: 'Merch',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.9,
    inStock: true,
    estimatedDelivery: '2 days',
  },
  {
    id: '4',
    sellerId: 'u2',
    name: 'Student Press Club Newsletter',
    description: 'Weekly subscription to campus news, gossip, and academic updates.',
    price: 200,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.2,
    inStock: true,
    estimatedDelivery: 'Instant',
  },
  {
    id: '5',
    sellerId: 'u2',
    name: 'Spicy Suya Plate (Large)',
    description: 'Hot spicy suya with onions and cabbage from the SUB pitch vendors. Delivered to hostel gate.',
    price: 3500,
    category: 'Food',
    image: 'https://picsum.photos/400/400?random=5',
    rating: 4.7,
    inStock: true,
    estimatedDelivery: '45 mins',
  },
  {
    id: '6',
    sellerId: 'u2',
    name: 'Rechargeable Fan',
    description: 'Essential for hot nights in Idia or Indy hall when the power fluctuates.',
    price: 8500,
    category: 'Hostel',
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.6,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '7',
    sellerId: 'u2',
    name: 'Scientific Calculator fx-991EX',
    description: 'Required for Faculty of Science and Tech students.',
    price: 15000,
    category: 'Gadgets',
    image: 'https://picsum.photos/400/400?random=7',
    rating: 5.0,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '8',
    sellerId: 'u2',
    name: 'Indomie & Egg Combo',
    description: 'The legendary "Hungry Man" size. Prepared at Kuti Hall buttery.',
    price: 1800,
    category: 'Food',
    image: 'https://picsum.photos/400/400?random=8',
    rating: 4.4,
    inStock: true,
    estimatedDelivery: '30 mins',
  },
  {
    id: '9',
    sellerId: 'u2',
    name: 'Bucket & Bowl Set',
    description: 'Sturdy plastic bucket for fetching water. A hostel necessity.',
    price: 3000,
    category: 'Hostel',
    image: 'https://picsum.photos/400/400?random=9',
    rating: 4.1,
    inStock: true,
    estimatedDelivery: 'Same day',
  },
  {
    id: '10',
    sellerId: 'u2',
    name: 'UI Varsity Jacket (Gold)',
    description: 'Limited edition gold and white varsity jacket.',
    price: 18000,
    category: 'Merch',
    image: 'https://picsum.photos/400/400?random=10',
    rating: 4.9,
    inStock: false,
    estimatedDelivery: '3-5 days',
  },
  {
    id: '11',
    sellerId: 'u2',
    name: 'Power Bank 20000mAh',
    description: 'Never run out of battery during long reading sessions at KDL.',
    price: 12000,
    category: 'Gadgets',
    image: 'https://picsum.photos/400/400?random=11',
    rating: 4.7,
    inStock: true,
    estimatedDelivery: '24 hours',
  },
  {
    id: '12',
    sellerId: 'u2',
    name: 'Past Questions Series (Science)',
    description: 'Compiled past questions and answers for 100L-400L science courses.',
    price: 1500,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=12',
    rating: 4.8,
    inStock: true,
    estimatedDelivery: 'Instant PDF',
  }
];
